apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: xi9pwfg10-go 
  janus-idp.io/tekton: xi9pwfg10-go
  backstage.io/kubernetes-id: xi9pwfg10-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: xi9pwfg10-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml