apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xi9pwfg10-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xi9pwfg10-go 
  name: xi9pwfg10-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xi9pwfg10-go 
